Repository aless2003/ktm_refurbished, pull requests merged in 2022-05, with the labels that each got.

#2 Created the Standard Layout used by all Views.
  build.gradle
  src/main/java/com/ktm/ktm_refurbished/KtmRefurbishedApplication.java
  src/main/java/com/ktm/ktm_refurbished/web/layouts/StandardLayout.java
  src/main/java/com/ktm/ktm_refurbished/web/views/HomeView.java
  src/main/resources/application.properties
  src/main/resources/vaadin-featureflags.properties
Labels: Frontend

#7 Merge MongoDB into Master
  mongoDB/docker-compose.yml
Labels: Docker, DB

#12 Marketplace
  src/main/java/com/ktm/ktm_refurbished/web/views/MarktView.java
  src/main/resources/application.properties
Labels: Frontend

#14 Login and Signup Views now have buttons to each other
  src/main/java/com/ktm/ktm_refurbished/web/views/LoginView.java
  src/main/java/com/ktm/ktm_refurbished/web/views/MarktView.java
  src/main/java/com/ktm/ktm_refurbished/web/views/SignUpView.java
Labels: Frontend

#15 Merge all of the Repos
  build.gradle
  frontend/css/sec.css
  frontend/css/standard.css
  src/main/java/com/ktm/ktm_refurbished/DataInput.java
  src/main/java/com/ktm/ktm_refurbished/KtmRefurbishedApplication.java
  src/main/java/com/ktm/ktm_refurbished/objects/Motorcycle.java
  src/main/java/com/ktm/ktm_refurbished/objects/MotorcyclePart.java
  src/main/java/com/ktm/ktm_refurbished/objects/MotorcyclePartStandardData.java
  src/main/java/com/ktm/ktm_refurbished/objects/MotorcycleSpecificData.java
  src/main/java/com/ktm/ktm_refurbished/objects/SpecificMotorcycle.java
  src/main/java/com/ktm/ktm_refurbished/repositories/MotorcyclePartRepository.java
  src/main/java/com/ktm/ktm_refurbished/repositories/MotorcyclePartStandardDataRepository.java
  src/main/java/com/ktm/ktm_refurbished/repositories/MotorcycleRepository.java
  src/main/java/com/ktm/ktm_refurbished/repositories/MotorcycleSpecificData.java
  src/main/java/com/ktm/ktm_refurbished/repositories/SpecificMotorcycleRepository.java
  src/main/java/com/ktm/ktm_refurbished/web/views/HomeView.java
  src/main/resources/docker-compose.yml
Labels: DB
